 CREATE TABLE `STOCK_PRICES_CATEGORIES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `STOCKDATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `OPEN` float DEFAULT '0',
  `HIGH` float DEFAULT '0',
  `LOW` float DEFAULT '0',
  `CLOSE` float DEFAULT '0',
  `VOLUME` bigint DEFAULT '0',
  PRIMARY KEY (`ID`)
)
